export enum Collections {
  storedays = 'storedays',
  alarms = 'alarms',
  areadays = 'areadays',
  areahours = 'areahours',
  attendance = 'attendance',
  attendancedays = 'attendancedays',
  attendancehour =  'attendancehour',
  coordinates = 'coordinates',
  devices = 'devices',
  elements = 'elements',
  exports = 'exports',
  imports = 'imports',
  masterdata = 'masterdata',
  sales = 'sales',
  storehours = 'storehours',
  timings = 'timings',
  totalattendance = 'totalattendance',
  tracks = 'tracks',
  useractivities = 'useractivities',
  viewstoredays = 'viewstoredays',
  weather = 'weather',
  websockets = 'websockets',
  wifi = 'wifi',
  storestatus = "storestatus",
  devicestatus = "devicestatus",
}
