import {
  CARDS_PAGE_SIZE_OPTIONS,
  PROPERTY_FILTERING_I18N_CONSTANTS,
} from '@visionarea-admin/frontend/shared/config';

export const COLUMN_DEFINITIONS = [
  {
    id: 'id',
    header: 'ID',
    cell: (e) => e.id,
    minWidth: 100,
    sortingField: 'id',
  },
  {
    id: 'Code',
    header: 'Code',
    cell: (e) => e.Code.trim(),
    minWidth: 100,
    sortingField: 'Code',
  },
  {
    id: 'Connected',
    header: 'Connected',
    cell: (e) => e.Connected,
    minWidth: 100,
    sortingField: 'Connected',
  },
  {
    id: 'Customers.Description',
    header: 'Customers',
    cell: (e) => e.Customers.Description,
    minWidth: 100,
    sortingField: 'Customers.Description',
  },
  {
    id: 'Code_Detector',
    header: 'Code Detector',
    cell: (e) => e.Code_Detector,
    minWidth: 100,
    sortingField: 'Code_Detector',
  },
  {
    id: 'Type',
    header: 'Type',
    cell: (e) => e.Type,
    minWidth: 100,
    sortingField: 'Type',
  },
  {
    id: 'Description',
    header: 'Description',
    cell: (e) => e.Description,
    minWidth: 100,
    sortingField: 'Description',
  },
  {
    id: 'TimeZone',
    header: 'TimeZone',
    cell: (e) => e.TimeZone,
    minWidth: 100,
    sortingField: 'TimeZone',
  },
  {
    id: 'IPLan',
    header: 'IP Lan',
    cell: (e) => e.IPLan,
    minWidth: 100,
    sortingField: 'IPLan',
  },
  {
    id: 'IPWan',
    header: 'IP WAN',
    cell: (e) => e.IPWan,
    minWidth: 100,
    sortingField: 'IPWan',
  },
  {
    id: 'TimeReset',
    header: 'Time Reset',
    cell: (e) => e.TimeReset,
    minWidth: 100,
    sortingField: 'TimeReset',
  },
  {
    id: 'Direction',
    header: 'Direction',
    cell: (e) => e.Direction,
    minWidth: 100,
    sortingField: 'Direction',
  },
  {
    id: 'Height',
    header: 'Height',
    cell: (e) => e.Height,
    minWidth: 100,
    sortingField: 'Height',
  },
  {
    id: 'User',
    header: 'User',
    cell: (e) => e.User,
    minWidth: 100,
    sortingField: 'User',
  },
  {
    id: 'Password',
    header: 'Password',
    cell: (e) => e.Password,
    minWidth: 100,
    sortingField: 'Password',
  },
  {
    id: 'Software',
    header: 'Software',
    cell: (e) => e.Software,
    minWidth: 100,
    sortingField: 'Software',
  },
  {
    id: 'Operation',
    header: 'Operation',
    cell: (e) => e.Operation,
    minWidth: 100,
    sortingField: 'Operation',
  },
  {
    id: 'TimeCall',
    header: 'TimeCall',
    cell: (e) => e.TimeCall,
    minWidth: 100,
    sortingField: 'TimeCall',
  },
  {
    id: 'BEAInDirection',
    header: 'BEAInDirection',
    cell: (e) => e.BEAInDirection,
    minWidth: 100,
    sortingField: 'BEAInDirection',
  },
];

export const FILTERING_PROPERTIES = [
  {
    propertyLabel: 'id',
    key: 'id',
    groupValuesLabel: 'id',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Code',
    key: 'Code',
    groupValuesLabel: 'Code',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Connected',
    key: 'Connected',
    groupValuesLabel: 'Connected',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Customers.Description',
    key: 'Customers.Description',
    groupValuesLabel: 'Customers.Description',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Code Detector',
    key: 'Code_Detector',
    groupValuesLabel: 'Code_Detector',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Type',
    key: 'Type',
    groupValuesLabel: 'Type',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Description',
    key: 'Description',
    groupValuesLabel: 'Description',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'TimeZone',
    key: 'TimeZone',
    groupValuesLabel: 'TimeZone',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'IPLan',
    key: 'IPLan',
    groupValuesLabel: 'IPLan',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'IPWan',
    key: 'IPWan',
    groupValuesLabel: 'IPWan',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'TimeReset',
    key: 'TimeReset',
    groupValuesLabel: 'TimeReset',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Direction',
    key: 'Direction',
    groupValuesLabel: 'Direction',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Height',
    key: 'Height',
    groupValuesLabel: 'Height',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'User',
    key: 'User',
    groupValuesLabel: 'User',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Password',
    key: 'Password',
    groupValuesLabel: 'Password',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Software',
    key: 'Software',
    groupValuesLabel: 'Software',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'Operation',
    key: 'Operation',
    groupValuesLabel: 'Operation',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'TimeCall',
    key: 'TimeCall',
    groupValuesLabel: 'TimeCall',
    operators: [':', '!:', '=', '!='],
  },
  {
    propertyLabel: 'BEAInDirection',
    key: 'BEAInDirection',
    groupValuesLabel: 'BEAInDirection',
    operators: [':', '!:', '=', '!='],
  },
];

export const FILTERING_CONSTANTS = PROPERTY_FILTERING_I18N_CONSTANTS;

export const VISIBLE_CONTENT_OPTIONS = [
  {
    label: 'Property',
    options: [
      { id: 'id', label: 'ID' },
      { id: 'Code', label: 'Code' },
      { id: 'Connected', label: 'Connected' },
      { id: 'Customers.Description', label: 'Customers' },
      { id: 'Code_Detector', label: 'Code Detector' },
      { id: 'Type', label: 'Type' },
      { id: 'Description', label: 'Description' },
      { id: 'TimeZone', label: 'Time Zone' },
      { id: 'IPLan', label: 'IP LAN' },
      { id: 'IPWan', label: 'IP WAN' },
      { id: 'TimeReset', label: 'Time Reset' },
      { id: 'Direction', label: 'Direction' },
      { id: 'Height', label: 'Height' },
      { id: 'User', label: 'User' },
      { id: 'Password', label: 'Password' },
      { id: 'Software', label: 'Software' },
      { id: 'Operation', label: 'Operation' },
      { id: 'TimeCall', label: 'TimeCall' },
      { id: 'BEAInDirection', label: 'BEAInDirection' },
    ],
  },
];

export const PAGE_SIZE_OPTIONS = CARDS_PAGE_SIZE_OPTIONS;

export const DEFAULT_PREFERENCES = {
  pageSize: 30,
  visibleContent: [
    'id',
    'Code',
    'Connected',
    'Customers.Description',
    'Type',
    'Code_Detector',
    'Description',
    'TimeZone',
    'IPLan',
    'IPWan',
    'TimeReset',
    'Direction',
    'Height',
    'User',
    'Password',
    'Software',
    'Operation',
    'TimeCall',
    'BEAInDirection',
  ],
};
